trigger:
  - master

variables:
  githubConnection: 'github.com_xmayeur'
  repositoryName: 'xmayeur/obs2ebird'
  tag: '0.2'
  title: 'v0.2'

jobs:
  - job: linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          echo 'building'
          sudo apt update && sudo apt remove python2 -y && sudo apt install python3-tk -y
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          ./build_linux.sh
          mv dist/o2eb dist/o2eb_linux_x64
        displayName: 'Linux obs2eBird build script'
      - template: pipeline-template.yml
        parameters:
          SourceFolder: '$(System.DefaultWorkingDirectory)/dist'
          Contents: 'o2eb_linux_x64'
          ArtifactName: 'Linux'

  - job: macos
    pool:
      vmImage: macOS-latest
    steps:
      - script: |
          
          brew install python-tk
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          ./build.sh
          rm -fr dist/o2eb
          cd dist
          zip -r o2eb_macos_x86.zip o2eb.app

        displayName: 'MacOS obs2eBird build script'
      - template: pipeline-template.yml
        parameters:
          SourceFolder: '$(System.DefaultWorkingDirectory)/dist'
          Contents: 'o2eb_macos_x86.zip'
          ArtifactName: 'MacOS'

  - job: windows
    pool:
      vmImage: windows-latest
    steps:
      - script: |
          pip install pyinstaller
          pip install -r requirements.txt
          build.bat
        displayName: 'Win obs2eBird build script'
      - template: pipeline-template.yml
        parameters:
          SourceFolder: '$(System.DefaultWorkingDirectory)/dist'
          Contents: 'o2eb.exe'
          ArtifactName: 'Windows'
