# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
jobs:
  - job: linux
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        pip install pyinstaller
        pip install -r requirements.txt
        ./build.sh
      displayName: 'Linux obs2eBird build script'
    - publish: $(System.DefaultWorkingDirectory)/dist/o2eb/
      artifact: o2eb_linux_x64
  - job: macos
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        pip install pyinstaller
        pip install -r requirements.txt
        ./build.sh
      displayName: 'MacOS obs2eBird build script'
    - publish: $(System.DefaultWorkingDirectory)/dist/
      artifact: o2eb.app
  - job: windows
    pool:
      vmImage: windows-latest
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        pip install pyinstaller
        pip install -r requirements.txt
        build.bat
      displayName: 'Win obs2eBird build script'
    - publish: $(System.DefaultWorkingDirectory)/dist/o2eb/
      artifact: o2eb_win_x64.exe